name: Run tests

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: 'Code is clean'
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - uses: actions/setup-go@v3
      with:
        check-latest: true
    - run: yarn
    - run: yarn fmt
    - run: ./scripts/fail_on_diff.sh

  tests:
    name: 'Run tests'

    strategy:
      matrix:
        os: [linux-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - uses: actions/setup-go@v3
      with:
        check-latest: true
    - run: go build
    - run: go test -race -cover
    # Test examples
    - run: go run main.go
      working-directory: ./examples/connecthook
    - run: go run main.go
      working-directory: ./examples/basic
