name: Run tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - run: ./scripts/ci/prepare_linux.sh
    - run: go test -race -cover
    - run: yarn
    - run: yarn fmt
    - run: ./scripts/fail_on_diff.sh
    # Test examples
    - run: go run main.go
      working-directory: ./examples/connecthook
    - run: go run main.go
      working-directory: ./examples/basic

  tests:
    runs-on:
      - ubuntu-latest
      - windows-latest
      - macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - uses: actions/setup-go@v3
      with:
        check-latest: true
    - run: go build
    - run: go test -race -cover
